apiVersion: v1
kind: ReplicationController
metadata:
   namespace: demos
   name: frontend
spec:
   replicas: 2
   template:
      metadata:
         labels:
            demo: frontend
      spec:
         containers:
         - name: frontend
           image: tomdee/money-maker

