apiVersion: v1
kind: ReplicationController
metadata:
   namespace: demos
   name: redis
spec:
   replicas: 1
   template:
      metadata:
         labels:
            demo: redis
      spec:
         containers:
         - name: redis
           image: redis:alpine

